src/tweet/fun.rs, src/user/fun.rs
This PR makes lookup functions like `user::lookup` take an iterator, instead of a slice. The change slightly reduces heap allocations in some cases.
Although this is, strictly speaking, a breaking change, it doesn't matter in most cases because `&'a [T]` implements `IntoIterator<Item=&'a T>`.
```rust
use egg_mode::user::{self, TwitterUser};
use egg_mode::{Token, WebResponse};
fn refresh_users_info(users: &[TwitterUser], token: &Token) -> WebResponse<Vec<TwitterUser>> {
// Previously, you had to make a `Vec` of user IDs:
// let ids: Vec<_> = users.iter().map(|u| u.id).collect();
// return user::lookup(&ids, token);
// Now, you can write like this:
let ids = users.iter().map(|u| u.id);
user::lookup(ids, token)
}
=> Make lookup functions take an iterator

src/search.rs
Even though official Twitter api documentation says it supports other
units than kilometer, tests shows using kilometer with floating point
numbers gives better results.
=> Change search distance fields to f32

Cargo.toml, src/search.rs
This change makes possible saving `SearchResults::max_id` for later use in
`SearchBuilder::since_tweet` by making `SearchResults::max_id` and 
`SearchResults::since_id` public.
PS: there is another pull request which includes `Change search distance fields to f32` please ignore that in this PR. Sorry about that.
=> Make `max_id` and `since_id` fields public in SearchResults

src/search.rs
Return value does not borrow anything from the old SearchResult value (as signatures without explicit lifetimes indicate due to lifetime elision rules), they just happen to have a copy of a reference stored
inside - and can have the same lifetime parameter as the original SearchResult value.
This would make code like this compile:
```rust
let mut result = search::search("foo").call(&token).unwrap();
loop {
// do something with result
// and load more
result = result.older().unwrap();
}
```
=> Fix improper lifetime on SearchResult methods

TODO.md
From what it sounds like these are intended to replace the existing direct message APIs at some point.
The new creation API supports sending message attachments which is neat.
The new list API returns 30 days back of message (instead of 200 max) and both send/received in one API call.
=> Add direct message events API to TODO

src/auth.rs
`PercentEncode` (returned value of `percent_encoding::utf8_percent_encode`) implements `Display` trait, so allocating a `String` is unnecessary when `format!`ing it.
=> Avoid `collect`ing `PercentEncode` into `String`

src/tweet/mod.rs, src/tweet/raw.rs, src/user/mod.rs, src/user/raw.rs
It seems Twitter have started serving up `null` for `lang` on tweets and users. This was a quick change to get [read-rust](https://github.com/wezm/read-rust) working again.
=> Make lang optional on tweet and user

sample_payloads/sample-image-alt-text.json, src/entities.rs, src/tweet/fun.rs, src/tweet/mod.rs
See https://blog.twitter.com/developer/en_us/a/2016/alt-text-support-for-twitter-cards-and-the-rest-api.html
Not sure why the Twitter docs don't mention the ext_alt_text field at https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#media , maybe they forgot to document it there?
I have not looked into test coverage yet.
=> fix(media): Add alt text support for accessibility

examples/common/mod.rs, src/entities.rs
=> fix(entities): Expanded URLs are sometimes null, represent them as Option

Cargo.toml, src/common/response.rs, src/error.rs, src/lib.rs
This PR adds a cargo feature that allows `native-tls` to be replaced with `hyper-rustls`, which describes itself as, "a pure-Rust HTTPS connector for hyper, based on Rustls". This allows `egg-mode` to be used without a transient dependency on openssl where that is what `native-tls` would choose, for example on FreeBSD and Linux. With `hyper-rustls` enabled this also makes egg-mode easier to cross compile as a cross-compiled version of openssl need not be made available.
The feature is used by adding `egg-mode` to a `Cargo.toml` like this (assuming this change has been merged and published into a theoretical version 0.12.1):
```
egg-mode = { version = "0.12.1", default-features = false, features = ["hyper-rustls"] }
```
Some tweaks the CI setup should probably be done to run tests with the …
=> Add support for hyper-rustls

src/list/mod.rs
The `deserialize_datetime` serde annotation was missing on a field, causing errors.
=> Deserialize lists properly (datetime format)

appveyor.yml, src/auth.rs, src/direct/fun.rs, src/direct/mod.rs, src/lib.rs, src/place/fun.rs, src/search.rs
I found some of the `Future` implementations hard to read. This replaces them with combinators, where feasible.
`TwitterFuture` and `RawFuture` are more involved (I quickly ran into lifetime issues) so are deferred for now.
=> Simplify futures implementations

Cargo.toml, src/common/response.rs, src/error.rs
This makes `hyper-tls` optional by introducing custom feature which is a bit incompatible as originally it used only `native-tls` to determine which TLS library to use, but that left `hyper-tls` to be dependency even if user would need only `rustls`
=> Make hyper-tls optional

examples/common/mod.rs, src/tweet/mod.rs, src/tweet/raw.rs
I encountered
```
DeserializeError(Error("Invalid response received: TweetSource had no link href (Some(\"\"))", line: 1, column: 339751))
```
when fetching users via `friends_of`, `followers_of`. 
The source attribute in tweets (that get pulled in via status tweets) can be empty instead of an `a` tag. In this case I think that parsing shouldn't fail. I think making the `TweetSource` optional would be a proper fix.
=> TweetSource optional

Cargo.toml, README.md, examples/basic.rs, examples/bearer.rs, examples/common/mod.rs, examples/conversations.rs, examples/lists.rs, examples/reciprocal.rs, examples/thread.rs, examples/tweets.rs, src/auth.rs, src/common/mod.rs, src/common/response.rs, src/cursor.rs, src/direct/fun.rs, src/direct/mod.rs, src/error.rs, src/lib.rs, src/list/fun.rs, src/list/mod.rs, src/media/mod.rs, src/place/fun.rs, src/place/mod.rs, src/search.rs, src/service.rs, src/stream/mod.rs, src/tweet/fun.rs, src/tweet/mod.rs, src/user/fun.rs, src/user/mod.rs
Big grab bag of changes.
* Remove almost all the methods around `Response` / `ResponseIter`. I didn't think these were pulling their weight given the extra complexity.
* Use `thiserror` to generate the `Error` type implementation. This involved removing the hard-deprecated `fn description` method.
* Remove all the lifetimes inside various structs (e.g. `UserID`, `ParamList` &c). The extra complexity of handling these lifetimes was making refactoring very tricky, and the performance gain is minimal
* pull the rate limit data into it's own `RateLimitStatus` type with the help of `#[serde(flatten)]`
* made `FutureResult` just an alias for `Pin<Box<dyn Future<Output=Result<T>>>>`. First step to removing as many `Future` and `Stream` implementations as possible and just using `async fn` …
=> Prepare for 0.14

CHANGELOG.md, examples/raw.rs, src/auth.rs, src/common/mod.rs, src/common/response.rs, src/direct/fun.rs, src/direct/mod.rs, src/lib.rs, src/list/fun.rs, src/raw.rs, src/stream/mod.rs, src/tweet/fun.rs, src/user/fun.rs
This PR creates a new `raw` module and re-exports a handful of internal functions (or wraps those internal functions with public wrappers). This should allow users to bind arbitrary endpoints\* that egg-mode doesn't currently wrap, or to add parameters that egg-mode doesn't currently use. I stopped short of exposing all of the internal `auth` module (cc https://github.com/egg-mode-rs/egg-mode/issues/32), because i had misgivings about the state of all that code. (Also i don't want to give the idea that egg-mode code can be used as a generic OAuth library; i don't want to support OAuth models other than Twitter, TBH.)
I also decided to rename the exports to follow a request/response dichotomy, since the functions i chose to expose did one of two things:
1. Assemble a web request (or take …
=> expose some internal request-/response-building functions

CHANGELOG.md, src/auth.rs, src/auth/raw.rs, src/common/mod.rs, src/raw.rs
Closes #32
This PR is the culmination of the work from #91 and #93. When i started egg-mode, i swore up and down that i didn't want to expose a generic OAuth mechanism, but while i was working on the `raw` module and the `auth` refactor, i noticed i could create something that was both easy-to-use and useful to the people who needed to use egg-mode for purposes we hadn't allowed or envisioned. I don't really want to extract this into its own crate unless people really want it for something other than Twitter, since i don't want to create the extra dependency for seemingly no reason.
As with everything i add to egg-mode, i tried to write compelling documentation to describe how to use it effectively. Part of the design of `RequestBuilder` was informed by my existing use of the auth …
=> expose a generic raw request builder

CHANGELOG.md, Cargo.toml, src/lib.rs
Closes #92
This PR updates `hyper-rustls` to allow for exposing its `native-tokio` and `webpki-tokio` features, as egg-mode features `rustls` and `rustls_webpki`, respectively. This does break existing rustls users, since the feature will need to be renamed from `hyper-rustls` to `rustls`, but i felt like it was necessary to allow for the webpki roots to be accessed.
I ran an example locally with all three configurations (the previously mentioned `rustls` configurations and the existing `native_tls` option) and they all seemed to work on my system. Hopefully this can help people who are in a similar situation as in #92.
=> update hyper-rustls and enable webpki-roots via crate features

CHANGELOG.md, examples/conversations.rs, src/auth/raw.rs, src/common/mod.rs, src/common/response.rs, src/direct/fun.rs, src/direct/mod.rs, src/direct/raw.rs, src/lib.rs, src/links.rs, src/media/mod.rs, src/raw.rs, src/raw/types/direct.rs
Back in 2018, Twitter introduced the new Account Activity API for Direct Messages, and deprecated the previous DM endpoints. egg-mode was never updated to use this new API, so when the old endpoints were shut off later that year, users couldn't use egg-mode to send and receive DMs any more.
This PR updates egg-mode's Direct Message functionality to use the new API. The functionality has been updated to reflect the new capabilities they added. Notably, it's no longer necessary to merge two different timelines to get a complete view of a user's Direct Messages - now there's a single `list` call that returns everything from the last 30 days. Also, now there are many things that can be added to a DM when you send it, including media, so the old `send` function has been converted into a …
=> overhaul the `direct` module to use the new API

README.md
Some function calls are missing their required `::auth` module prefix.
Great library, by the way! I'm new to Rust, so playing around with it has been a great way for me to learn the language.
=> Update README to reflect library changes

CHANGELOG.md, sample_payloads/tweet_array.json, sample_payloads/user_array.json, src/common/mod.rs, src/direct/raw.rs, src/entities.rs, src/list/mod.rs, src/place/mod.rs, src/raw.rs, src/stream/mod.rs, src/tweet/mod.rs, src/tweet/raw.rs, src/user/mod.rs, src/user/raw.rs
Closes #90 
This PR adds a `Serialize` impl for various types in the library, most notably `Tweet` and `TwitterUser`. Since those types have existing `Deserialize` impls that load via a "raw" type that mirrors Twitter's JSON representation, i needed to introduce a new mechanism to allow loading via *either* Twitter's JSON *or* egg-mode's.
The way i did this for this PR was to introduce a new `round_trip!` macro that wrapped the structs and added some new items used internally by the macro:
* `SerCopy`, a field-for-field copy of the given type,
* `SerEnum`, an enum which can either be the "raw" type or `SerCopy`,
* and a couple derived `Deserialize` implementations that leverage the `#[serde(untagged)]` attribute to drive the deserialization.
One major drawback with this approach is that …
=> impl Serialize for Tweet/TwitterUser

src/user/fun.rs
Closes https://github.com/egg-mode-rs/egg-mode/issues/96
Looks like this was missed in the initial Serde conversion. The relationship info returned by Twitter is wrapped in an object that has a single `"relationship"` field with the data we actually return. The original `FromJson` impl accounted for this, but when it was replaced with a straight `#[derive(Deserialize)]`, it broke that endpoint. This PR creates the proper wrapper struct when loading the relationship data.
=> properly deserialize Relationship in user::relation

src/cursor.rs
This allows using the CursorIter in a Send future.
=> Add missing Send bounds for CursorIter.

CONTRIBUTING.md, TODO.md, src/entities.rs, src/error.rs, src/place/mod.rs, src/search.rs, src/service.rs, src/user/mod.rs, src/user/raw.rs
Update links to the old API documentation to point to the correct page.
Closes https://github.com/egg-mode-rs/egg-mode/issues/37
=> Update links to API docs

CHANGELOG.md, Cargo.toml, examples/create_tweet.rs, src/auth/raw.rs, src/common/response.rs, src/error.rs
My pull request generally bumps all outdated dependencies, but most importantly it updates to tokio v1.0.
=> Update to tokio version 1.0

src/entities.rs
I needed to filter media by type and had to add this derive to get it working. Also derived on ResizeMode since it's a similarly shaped enum.
=> Derive PartialEq on MediaType and ResizeMode

src/lib.rs, src/links.rs, src/trend/fun.rs, src/trend/mod.rs, src/trend/raw.rs
Since the API is needed by myself, I try to add [`trend/closest`](https://developer.twitter.com/en/docs/twitter-api/v1/trends/locations-with-trending-topics/api-reference/get-trends-closest) and [`trend/available`](https://developer.twitter.com/en/docs/twitter-api/v1/trends/locations-with-trending-topics/api-reference/get-trends-available) in the new patch.
I may make some errors since I am not so familiar with the API and only implement it to meet my requirement. So I sincerely appreciate your review, and it's fine to point out if there are any bad or improvable codes/documents. I'll try to figure it out and fix them!
=> Implement API for getting locations with trending topics
